table = "dim_item"
schema = "public"
database = "query_builder"
table_type = "dimesion"

[fields]
sk_item_id = {type = "select", show = "false"}
bk_item_id = {type = "select",show = "false"}
bk_item_name = {type = "select",show = "true", name="Название товара"}
bk_combined_map = {type = "groupping", name="Жанр", show="true", exclude_from_group = ["sk_account_id", "bk_account_id", "bk_account_name"], same_field="query_builder.public.dim_item.dim_account"}
