table = "dim_calendar"
schema = "public"
database = "query_builder"
table_type = "dimension"

[fields]
id = {type = "select", show = "false"}
date = {type = "select", show = "true", name="Дата", show_group="Календарь"}
week_no = {type = "select", show = "true", name="Номер недели", show_group="Календарь"}
first_day_of_week = {type = "select", show = "true", name="Первый день недели", show_group="Календарь"}
last_day_of_week = {type = "select", show = "true", name="Последний день недели", show_group="Календарь"}
first_day_of_month = {type = "select", show = "true", name="Первый день недели", show_group="Календарь"}
last_day_of_month = {type = "select", show = "true", name="Последний день недели", show_group="Календарь"}
month = {type = "select", show = "true", name="Месяц", show_group="Календарь"}
year = {type = "select", show = "true", name="Год", show_group="Календарь"}
