table = "dim_item"
schema = "public"
database = "query_builder"
table_type = "dimension"

[fields]
id = {type = "select", show = "false"}
sk_item_id = {type = "select", show = "false"}
name = {type = "select", show = "true", name="Название товара", show_group="Товар"}
volume = {type = "select", show = "true", name="Объем товара, м3", show_group="Товар"}
price = {type = "select", show = "true", name="Цена товара, руб.", show_group="Товар"}
