table = "fact_sales"
schema = "public"
database = "query_builder"
table_type = "data"

[fields]
id = {type = "select", show = "false"}
sk_item_id = {type = "select", show = "false"}
sk_store_id = {type = "select", show = "false"}
value = {type = "select", show = "true", name="Продажа. Кол-во шт.", show_group="Продажи"}
money = {type = "select", show = "true", name="Продажа. Сумма руб.", show_group="Продажи"}
date = {type = "select", show = "false"}
