table = "fact_stock"
schema = "public"
database = "query_builder"
table_type = "data"

[fields]
id = {type = "select", show = "false"}
sk_item_id = {type = "select", show = "false"}
sk_warehouse_id = {type = "select", show = "false"}
value = {type = "value", show = "true", name="Запасы. Кол-во шт."}
date = {type = "select", show = "false"}

[calculations]
last_day_of_week_pcs = {type = "calculation", show = "true", calculation = "sum(query_builder.public.fact_stock.value)", where = "dim_calendar.last_day_of_week = 1", fact_must_join_on = "dim_calendar.week_no, dim_calendar.year", no_join_fact = "dim_calendar.date", name="Запасы на последний день недели, шт"}
first_day_of_week_pcs = {type = "calculation", show = "true", calculation = "sum(query_builder.public.fact_stock.value)", where = "dim_calendar.first_day_of_week = 1", fact_must_join_on = "dim_calendar.week_no, dim_calendar.year", no_join_fact = "dim_calendar.date", name="Запасы на последний день недели, шт"}
last_day_of_week_rub = {type = "calculation", show = "true", calculation = "sum(query_builder.public.fact_stock.value * query_builder.public.item.price)", where = "dim_calendar.last_day_of_week = 1", fact_must_join_on = ["dim_calendar.week_no", "dim_calendar.year"], no_join_fact = "dim_calendar.date", name="Запасы на последний день недели, руб"}
first_day_of_week_rub = {type = "calculation", show = "true", calculation = "sum(query_builder.public.fact_stock.value * query_builder.public.item.price)", where = "dim_calendar.first_day_of_week = 1", fact_must_join_on = ["dim_calendar.week_no", "dim_calendar.year"], no_join_fact = "dim_calendar.date", name="Запасы на последний день недели, руб"}
