table = "dim_store"
schema = "public"
database = "query_builder"
table_type = "dimesion"

[fields]
id = {type = "select", show = "false"}
sk_store_id = {type = "select", show = "false"}
bk_address = {type = "select", show = "true", name="Номер магазина"}
address = {type = "select", show = "true", name="Адрес магазина"}
