table = "fact_stock"
schema = "public"
database = "query_builder"
table_type = "data"

[fields]
id = {type = "select", show = "false"}
sk_item_id = {type = "select", show = "false"}
sk_warehouse_id = {type = "select", show = "false"}
value = {type = "select", show = "true", name="Запасы. Кол-во шт."}
date = {type = "select", show = "false"}
