filter_name = "filter_one"
front_end_name = "Первый настроенный фильтр"
tables_list = ["query_builder.public.dim_store", "query_builder.public.dim_item"]
where_query = "query_builder.public.dim_store.store_id = 1 and query_builder.public.dim_item.price > 1000"