version: '3.1'

services:
  db_query_builder:
    container_name: 'db_query_builder'
    image: 'postgres:15-bullseye'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'query_builder'
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
